### ISSUE TITLE
Parallel port (Win 64 / Python 3.5)

### ISSUE THREAD

**Issue by smathot** [expyriment/expyriment#71]
I just gave the Python 3 branch a test spin, using Python 3.5 64 bit. It seems to work quite nicely within OpenSesame, except for a problem with initializing parallel port. The offending line is here:

-  https://github.com/expyriment/expyriment/blob/python3/expyriment/io/_parallelport/__init__.py#L47

But I think it highlights a more general problem, namely that a lot of modules/ packages are automatically loaded, even if they are not necessary. This makes the startup process quite sluggish. Would it be possible to make this more modular, so that you can use only a select set of modules?

**Comment by lindemann09** [comment]
I fixed the import bug. 

Expyriment still tries to import all modules and submodules, but  does now not crash, if there are any problems. The full import philosophy was introduced to ensure that users see via the autocompletion function of their programming IDE which modules and options are provided. That is actually very convenient. I will however discuss with Florin next week this approach.

**Comment by fladd** [comment]
Hi Sebastiaan,

I would really like to know why line 47 crashes for you? So it does find the dlportio dll, but then still cannot use it with ctypes?

**Comment by lindemann09** [comment]
line 47 is: 
```
        from ._inpout32 import PParallelInpOut32 
```

**Comment by fladd** [comment]
In that case, I am wondering the same thing, except for the inpout32 dll :-)
